{
 "title": "TrueNAS Scale - Graphite",
 "description": "TrueNAS Scale Dashboard, using the default Graphite options in TrueNAS Scale.\nhttps://grafana.com/grafana/dashboards/20439-truenas-scale/\nSee me @ blog.filegarden.net",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "TrueNAS",
    "label": "Truenas System",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Docker CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "servers.truenas_main.services.cpu.docker"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 7, "y": 1 },
   "targets": [
    {
     "target": "servers.truenas_main.services.mem_usage.docker"
    }
   ]
  },
  { "title": "ZFS / ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Byteheaven Faulted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(servers.*.zfspool.state_Bytehaven.faulted)"
    }
   ]
  },
  {
   "title": "ARC Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "servers.*.zfs.arc_size.arcsz" }
   ]
  },
  {
   "title": "ZFS ARC Result - Demand Data",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByMetric(servers.*.zfs.actual_hits.*)"
    }
   ]
  },
  {
   "title": "ZFS Status Boot",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(servers.*.zfspool.state_boot_pool.*)"
    }
   ]
  },
  {
   "title": "Active Processes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "servers.*.system.active_processes.active"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "servers.*.system.uptime.uptime" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(servers.*.cpu.cpu0.idle)"
    },
    {
     "target": "aliasByMetric(servers.*.cpu.*.iowait)"
    },
    {
     "target": "aliasByMetric(servers.*.cpu.*.nice)"
    },
    {
     "target": "aliasByMetric(servers.*.cpu.*.system)"
    },
    {
     "target": "aliasByMetric(servers.*.cpu.*.user)"
    },
    {
     "target": "aliasByMetric(servers.*.cpu.*.softirq)"
    }
   ]
  },
  {
   "title": "CPU  Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByMetric(servers.*.cputemp.temperatures.*)"
    }
   ]
  },
  {
   "title": "CPU  Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByMetric(servers.*.cpu.cpu0.idle)"
    },
    {
     "target": "aliasByMetric(servers.*.cpu.*.iowait)"
    },
    {
     "target": "aliasByMetric(servers.*.cpu.*.nice)"
    },
    {
     "target": "aliasByMetric(servers.*.cpu.*.system)"
    },
    {
     "target": "aliasByMetric(servers.*.cpu.*.user)"
    },
    {
     "target": "aliasByMetric(servers.*.cpu.*.softirq)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "RAM  Utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(servers.*.system.ram.free)"
    },
    {
     "target": "aliasByMetric(servers.*.system.ram.used)"
    },
    {
     "target": "aliasByMetric(servers.*.system.ram.cached)"
    },
    {
     "target": "aliasByMetric(servers.*.system.ram.buffers)"
    }
   ]
  },
  {
   "title": "Memory Swap Space",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(servers.*.system.swap)"
    }
   ]
  },
  {
   "title": "RAM  Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "target": "aliasByMetric(servers.*.system.ram.*)"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Disk Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(servers.truenas_main.smart_log_smart.*.*.*)"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(servers.*.disk_util.*.utilization, 2, 3, 4)"
    }
   ]
  },
  {
   "title": "Disk I/O Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Kibits" } },
   "targets": [
    {
     "target": "aliasByNode(servers.*.disk.*.*, 2, 3, 4)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "target": "aliasByNode(servers.*.net.*.*, 2, 3, 4)"
    }
   ]
  }
 ]
}